### ISSUE TITLE
Screenshots appear white on iOS Safari 18.0.1

### ISSUE THREAD

**Issue by max-got** [sveltejs/svelte.dev#527]
### Describe the Problem
Screenshots on svelte.dev show up completely white on iOS Safari 18.0.1. Interestingly, everything works fine in dev mode (`pnpm dev --host` (???)) .

<details>
<summary>Image</summary>

![svelte_dev_safari](https://github.com/user-attachments/assets/ce661b8b-e588-444c-8690-f44d4b3f027f)

</details>

### Describe the proposed solution
Could try changing `--safari-fix` to `translateZ(0)`. However, I can't verify if this works since the dev environment doesn't reproduce the issue and the repo doesn't let me `pnpm build && pnpm preview` the site.

### Reproduction
1. Visit svelte.dev on iOS Safari
3. Current CSS:
```css
.screenshots {
/* ... */
  filter: grayscale();
  -webkit-transform: var(--safari-fix); /* = translate3d(0,0,.01) */
}
```

### System Info
- Device: iPhone 11 Pro
- OS: iOS 18.0.1
- Browser: Safari
- URL: [svelte.dev](https://svelte.dev)
